export const pendingEmployeesData = [
	{ fullName: "Nhat Huynh (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Linh Nguyen (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Thy Nguyen (EG - HR)", jobTitle: "Human Resources Specialist" },
	{ fullName: "Kim Le (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Han Tran (EHUB - MKT)", jobTitle: "Marketing Executive" },
	{ fullName: "Thanh Do (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "Huy Nguyen (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Linh Van (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Kien Nguyen (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Tram Le (TMS - BD)", jobTitle: "Marketing Executive" },
	{ fullName: "Huyen Ngo (ES - SP)", jobTitle: "Barista Staff" },
	{ fullName: "Chinh Nguyen (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Nguyen Truong (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Chi Nguyen (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "Khanh Nguyen (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "Thang Nguyen (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Linh Nguyen (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Ba Le (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Dat Van (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Tam Dang (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Uyen Nguyen (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Phuong Nguyen (EHUB - ML/AI)", jobTitle: "AI Engineer" },
	{ fullName: "Ngan Nguyen (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Sinh Nguyen (EHUB - BD)", jobTitle: "Business Development Executive" },
	{ fullName: "Quy Do (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Uyen Vuong (EHUB - DS)", jobTitle: "Graphic Designer" },
	{ fullName: "Trinh Le (EG - HR)", jobTitle: "Human Resources Administrator" },
	{ fullName: "Bao Nguyen (EHUB - DS)", jobTitle: "Graphic Designer" },
	{ fullName: "Mai Truong (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Long Nguyen (EG - HR)", jobTitle: "IT Helpdesk" },
	{ fullName: "Hau Tran (EHUB - DS)", jobTitle: "Graphic Designer" },
	{ fullName: "Chuong Mai (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Sang Vuong (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Toan Huynh (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Dung Ngo (EG - FA)", jobTitle: "Finance & Account Admin" },
	{ fullName: "Phu Mai (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Hoang Nguyen (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Viet Nguyen (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Thao Mac (ES - SP)", jobTitle: "Space Community Intern" },
	{ fullName: "Van Dinh (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "Ha Tran (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Tung Ho (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Cuong Vu (ES - SP)", jobTitle: "Space Operation Staff" },
	{ fullName: "Dung Tran (EHUB - MO)", jobTitle: "Mobile Engineer" },
	{ fullName: "Thanh Nguyen (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "An Nguyen (EHUB - AM)", jobTitle: "Account Executive" },
	{ fullName: "Nhi Vo (ES - SP)", jobTitle: "Barista Staff" },
	{ fullName: "Trung Bui (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Thi Tran (EG - FA)", jobTitle: "General Accountant" },
	{ fullName: "Nguyen Tran (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Hoang Nguyen (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Nhi Pham (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Mai Ho (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Diep Vu (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "My Tu (ES - SP)", jobTitle: "Space Operation Staff" },
	{ fullName: "Huy Le (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Lan Tran (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Amit Kothari (EHUB - CTO)", jobTitle: "Chief Technology Officer" },
	{ fullName: "Hang Do (EG - HR)", jobTitle: "Employee Experience Specialist" },
	{ fullName: "Linh Do (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Hien Le (EHUB - AM)", jobTitle: "Account Executive" },
	{ fullName: "Lam Le (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Phuc Pham (EG - CA)", jobTitle: "CEO Assistant - Business Development Coordinator" },
	{ fullName: "Nhan Phan (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Nhan Dinh (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Linh Duong (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Truc Nguyen (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Thuy Vo (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Van Tran (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Nguyet Pham (EHUB - ML/AI)", jobTitle: "AI Engineer" },
	{ fullName: "Tai Vo (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Trang Nguyen (EHUB - FE)", jobTitle: "Frontend Engineer" },
	{ fullName: "Quynh Vo (TMS - CEO)", jobTitle: "Chief Executive Officer" },
	{ fullName: "My Le (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Ha Nguyen (EHUB - MO)", jobTitle: "Mobile Engineer" },
	{ fullName: "Trang Nguyen (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Huong Nguyen (EG - CA)", jobTitle: "CEO Assistant - Finance Coordinator" },
	{ fullName: "Hieu Nguyen (EHUB - PDO Intern)", jobTitle: "Software Engineer Intern" },
	{ fullName: "Thao Ho (EG - HR)", jobTitle: "Talent Acquisition Specialist" },
	{ fullName: "Vy Huynh (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Huy Nguyen (EHUB - MO)", jobTitle: "Mobile Engineer" },
	{ fullName: "Hanh Nguyen (ES - SP)", jobTitle: "Barista Staff" },
	{ fullName: "Diem Do (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Thuan Nguyen (EHUB - MO)", jobTitle: "Mobile Engineer" },
	{ fullName: "Tra Pham (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Ty Nguyen (EHUB - BE)", jobTitle: "DevOps Engineer" },
	{ fullName: "Tri Le (EHUB - MKT)", jobTitle: "Digital Marketing Executive" },
	{ fullName: "Bich Ho (EHUB - QA)", jobTitle: "Quality Assurance Engineer" },
	{ fullName: "Dat Vo (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Ngoc Dang (EHUB - BD)", jobTitle: "Business Development Executive" },
	{ fullName: "Long Huynh (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Quang Nguyen (EHUB - DS)", jobTitle: "Creative Designer" },
	{ fullName: "Tuyen Tran (EHUB - PA)", jobTitle: "Business Analyst" },
	{ fullName: "Tram Vo (EG - CA)", jobTitle: "CEO Assistant - Personal cum P&C" },
	{ fullName: "Dung Thai (EG - FA)", jobTitle: "Finance & Accounting" },
	{ fullName: "Nhu Ha (EHUB - DS)", jobTitle: "Product Designer" },
	{ fullName: "Nam Phan (EHUB - BE)", jobTitle: "Backend Engineer" },
	{ fullName: "Hai Huynh (EHUB - WD)", jobTitle: "Web Developer" },
	{ fullName: "Chi Hoang (TMS - CS)", jobTitle: "Customer Success Executive" },
	{ fullName: "Thien Pham (EHUB - FE)", jobTitle: "Frontend Engineer" },
];
