import { RoleType } from "@prisma/client";
import { DemoConfig } from "../../config";

export const userData = [
	{
		fullName: "Trang Tran (EG - CEO)",
		jobTitle: "Chief Executive Officer",
		employeeCode: "EHUB0001",
		email: "trang.tran@ehub.com",
		lineManager: null,
		joinedAt: "2023-02-18T22:47:47.563Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: DemoConfig.HR_ADMIN.FULLNAME,
		jobTitle: DemoConfig.HR_ADMIN.JOB_TITLE,
		employeeCode: "EHUB1000",
		email: DemoConfig.HR_ADMIN.EMAIL,
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2023-02-18T22:47:47.563Z",
		role: RoleType.HR_ADMIN,
	},
	{
		fullName: "Anh Nguyen (EG - HR)",
		jobTitle: "Human Resource Manager",
		employeeCode: "EHUB0514",
		email: "anh.nguyen@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-04-25T09:24:00.381Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "MinhMai Phan (TMS - CPO)",
		jobTitle: "Chief Product Officer",
		employeeCode: "EHUB0067",
		email: "minh.phan@ehub.com",
		lineManager: null, // CPO — top-level executive, no line manager
		joinedAt: "2024-04-11T18:35:56.369Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "My Le (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "EHUB0299",
		email: "my.le@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2026-06-10T09:49:30.725Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thi Vi (EG - HR)",
		jobTitle: "Internal Communication Specialist",
		employeeCode: "EHUB0118",
		email: "thi.vi@team.ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2024-02-29T10:33:29.322Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Chuong Vo (TMS - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0231",
		email: "chuong.vo@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2022-11-07T04:42:31.648Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Phu Mai (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0033",
		email: "phu.mai@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2024-03-04T09:03:08.831Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tuyen Vo (EHUB - AM)",
		jobTitle: "Account Manager",
		employeeCode: "EHUB0006",
		email: "tuyen.vo@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2024-11-01T22:11:49.323Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Tri Le (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "",
		email: "tri.le@team.ehub.com",
		lineManager: "Thi Ho (TMS - BD)",
		joinedAt: "2024-06-21T10:16:52.964Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Khanh Nguyen (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0307",
		email: "khanhhuu.nguyen@team.ehub.com",
		lineManager: "Nhung Phan (EHUB - DS)",
		joinedAt: "2023-11-12T05:44:54.029Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Bao Nguyen (EHUB - DS)",
		jobTitle: "Graphic Designer",
		employeeCode: "EHUB0358",
		email: "bao.nguyen@team.ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2023-01-16T18:28:58.423Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: DemoConfig.PROJECT_MANAGER.FULLNAME,
		jobTitle: DemoConfig.PROJECT_MANAGER.JOB_TITLE,
		employeeCode: "EHUB0415",
		email: DemoConfig.PROJECT_MANAGER.EMAIL,
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2022-10-04T02:48:20.313Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Uyen Nguyen (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "EHUB0356",
		email: "uyen.nguyen@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2023-05-27T22:55:01.738Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Sao Nguyen (EHUB - DS)",
		jobTitle: "Design Lead",
		employeeCode: "EHUB0178",
		email: "sao.nguyen@ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2025-05-10T17:30:55.263Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Phat Nguyen (EHUB - FE)",
		jobTitle: "Frontend Chapter Lead",
		employeeCode: "EHUB0148",
		email: "phat.nguyen@ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-04-20T04:41:46.532Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Trinh Le (EG - HR)",
		jobTitle: "Human Resources Administrator",
		employeeCode: "EHUB0261",
		email: "trinh.le@ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2022-10-06T06:10:45.074Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Loan Ngo (TMS - CS)",
		jobTitle: "Operation & Customer Lead",
		employeeCode: "EHUB0267",
		email: "loan.ngo@ehub.com",
		lineManager: "MinhMai Phan (TMS - CPO)",
		joinedAt: "2026-03-01T03:38:48.253Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Tien Le (TMS - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0309",
		email: "tien.le@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2023-01-26T09:16:12.176Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "An Nguyen (EHUB - AM)",
		jobTitle: "Account Executive",
		employeeCode: "EHUB0379",
		email: "an.nguyen@team.ehub.com",
		lineManager: "Van Nguyen (EHUB - AM)",
		joinedAt: "2023-06-23T15:26:01.895Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhung Phan (EHUB - DS)",
		jobTitle: "Design Operations",
		employeeCode: "EHUB0024",
		email: "nhung.phan@ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2026-04-15T10:40:56.645Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Hang Do (EG - HR)",
		jobTitle: "Employee Experience Specialist",
		employeeCode: "EHUB0211",
		email: "hang.do@team.ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2023-09-05T08:56:45.310Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: DemoConfig.LINE_MANAGER.FULLNAME,
		jobTitle: DemoConfig.LINE_MANAGER.JOB_TITLE,
		employeeCode: "EHUB0038",
		email: DemoConfig.LINE_MANAGER.EMAIL,
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-01-06T12:57:01.124Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Chinh Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0296",
		email: "chinh.nguyen@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2023-11-19T02:03:48.001Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Van Nguyen (EHUB - AM)",
		jobTitle: "Account Manager",
		employeeCode: "EHUB0186",
		email: "van.nguyen@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-03-28T04:31:55.494Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Linh Tran (TMS - PM)",
		jobTitle: "Project Manager",
		employeeCode: "EHUB0022",
		email: "linh.tran@sotrams.ecaps",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2023-05-21T06:02:29.434Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Tram Vo (EG - CA)",
		jobTitle: "CEO Assistant - Personal cum P&C",
		employeeCode: "EHUB0382",
		email: "tram.vo@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2024-12-29T04:28:59.768Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Quang Nguyen (EHUB - DS)",
		jobTitle: "Creative Designer",
		employeeCode: "EHUB0039",
		email: "quang.nguyen@team.ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2024-09-03T15:43:29.322Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huyen Cao (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0122",
		email: "huyen.cao@ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2024-01-06T00:05:08.800Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Tran (TMS - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0242",
		email: "dungvan.tran@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2026-05-17T12:09:25.986Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thuy Vo (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0350",
		email: "thuy.vo@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-12-24T07:04:28.648Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ny Le (EHUB - PM)",
		jobTitle: "Project Coordinator",
		employeeCode: "EHUB0203",
		email: "ny.le@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2024-05-23T16:45:58.081Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Hau Tran (EHUB - DS)",
		jobTitle: "Graphic Designer",
		employeeCode: "EHUB0097",
		email: "hau.tran@team.ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2024-05-01T11:48:32.070Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Cuong Vu (ES - SP)",
		jobTitle: "Space Operation Staff",
		employeeCode: "EHUB0308",
		email: "cuong.vu@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2024-04-02T03:57:20.740Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thanh Le (ES - SP)",
		jobTitle: "Space Manager",
		employeeCode: "EHUB0435",
		email: "thanh.le@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-06-20T19:27:45.111Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Tam Dang (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "EHUB0306",
		email: "tam.dang@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2023-01-31T20:23:29.014Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhu Nguyen (TMS - BD)",
		jobTitle: "Solution Consultant",
		employeeCode: "EHUB0196",
		email: "nhu.nguyen@team.ehub.com",
		lineManager: "Loan Ngo (TMS - CS)",
		joinedAt: "2022-11-01T23:56:43.097Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Mai Truong (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0156",
		email: "mai.truong@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2024-10-21T10:01:37.653Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Le (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0409",
		email: "huudung.le@ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-08-25T05:27:52.790Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Le (EHUB - PIDO)",
		jobTitle: "Product Ideation & Design Office Manager",
		employeeCode: "EHUB0108",
		email: "dung.le@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2025-01-09T22:46:17.382Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Ngan Ho (EHUB - PM)",
		jobTitle: "Project Coordinator",
		employeeCode: "EHUB0373",
		email: "ngan.ho@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2026-06-23T00:38:20.224Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Uyen Vuong (EHUB - DS)",
		jobTitle: "Graphic Designer",
		employeeCode: "EHUB0147",
		email: "uyen.vuong@team.ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2023-07-14T14:50:45.694Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thi Tran (EG - FA)",
		jobTitle: "General Accountant",
		employeeCode: "EHUB0366",
		email: "thi.tran@ehub.com",
		lineManager: "Phuong Huynh (EG - FA)",
		joinedAt: "2023-11-09T22:13:41.698Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Toan Huynh (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0167",
		email: "toan.huynh@ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-02-21T05:38:24.243Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Long Huynh (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0065",
		email: "long.huynh@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2023-08-17T13:12:55.332Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huyen Ngo (ES - SP)",
		jobTitle: "Barista Staff",
		employeeCode: "EHUB0288",
		email: "huyen.ngo@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2025-03-29T07:32:23.052Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "A Not (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0032",
		email: "a.not@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-03-29T22:53:14.531Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nguyet Pham (EHUB - ML/AI)",
		jobTitle: "AI Engineer",
		employeeCode: "EHUB0215",
		email: "nguyet.pham@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-05-14T13:01:07.082Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ha Nguyen (EHUB - MO)",
		jobTitle: "Mobile Engineer",
		employeeCode: "EHUB0154",
		email: "ha.nguyen@team.ehub.com",
		lineManager: "Hai Nguyen (EHUB - MO)",
		joinedAt: "2025-09-26T08:04:23.325Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Uyen Huynh (EG - CA)",
		jobTitle: "CEO Assistant - Partnership & Community Lead",
		employeeCode: "EHUB0436",
		email: "uyen.huynh@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2024-12-27T15:00:37.139Z",
		role: "FUNCTION_LEAD",
	},
	{
		fullName: "Nguyen Truong (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0340",
		email: "nguyen.truong@ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2024-03-27T06:25:42.428Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Trang Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0105",
		email: "trangmy.nguyen@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-08-30T07:03:13.603Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hai Ta (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0304",
		email: "hai.ta@ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-04-24T02:51:07.886Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thanh Nguyen (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0142",
		email: "thanh.nguyen@team.ehub.com",
		lineManager: "Nhung Phan (EHUB - DS)",
		joinedAt: "2023-12-02T00:29:25.202Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Tran (EHUB - MO)",
		jobTitle: "Mobile Engineer",
		employeeCode: "EHUB0162",
		email: "dung.tran@team.ehub.com",
		lineManager: "Hai Nguyen (EHUB - MO)",
		joinedAt: "2025-01-24T23:37:49.918Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Mai Ho (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0164",
		email: "mai.ho@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2022-11-13T18:10:24.549Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hanh Tran (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0049",
		email: "hanh.tran@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-02-26T18:44:04.226Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Long Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0401",
		email: "longhoang.nguyen@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2025-07-25T10:26:06.150Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Long Nguyen (EG - HR)",
		jobTitle: "IT Helpdesk",
		employeeCode: "EHUB0117",
		email: "long.nguyen@team.ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2023-05-19T00:48:39.329Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Kim Le (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0063",
		email: "kim.le@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2022-11-01T03:18:34.107Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hai Huynh (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0241",
		email: "hai.huynh@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2023-02-08T09:11:53.803Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Viet Truong (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0425",
		email: "viet.truong@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2023-03-20T09:07:44.397Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Linh Duong (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0325",
		email: "linh.duong@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2025-06-23T19:24:26.557Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thang Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0441",
		email: "thang.nguyen@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-02-24T07:59:22.951Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dat Le (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0440",
		email: "dat.le@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2026-05-09T16:17:16.828Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhan Phan (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0442",
		email: "nhan.phan@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-08-24T00:34:41.830Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhu Ha (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0271",
		email: "nhu.ha@ehub.com",
		lineManager: "Nhung Phan (EHUB - DS)",
		joinedAt: "2025-08-25T20:06:57.140Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thien Pham (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0265",
		email: "thien.pham@ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-05-12T06:01:21.813Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tung Ho (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0443",
		email: "tung.ho@ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2026-06-30T19:12:08.831Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dat Van (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0450",
		email: "dat.van@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-02-29T09:27:16.911Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Chi Nguyen (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0479",
		email: "chi.nguyen@team.ehub.com",
		lineManager: "Nhung Phan (EHUB - DS)",
		joinedAt: "2023-04-25T13:48:21.197Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Chi Hoang (TMS - CS)",
		jobTitle: "Customer Success Executive",
		employeeCode: "EHUB0481",
		email: "chi.hoang@team.ehub.com",
		lineManager: "MinhMai Phan (TMS - CPO)",
		joinedAt: "2025-08-04T23:56:31.329Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thanh Nguyen (ES - SP)",
		jobTitle: "Maintenance Lead",
		employeeCode: "EHUB0041",
		email: "thuthanh.nguyen@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2024-12-10T20:42:02.711Z",
		role: "FUNCTION_LEAD",
	},
	{
		fullName: "Ha Nguyen (EG - CFO)",
		jobTitle: "CFO",
		employeeCode: "EHUB0491",
		email: "ha.nguyen@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2023-10-19T14:07:44.701Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Bich Ho (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0421",
		email: "bich.ho@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2024-05-03T18:19:12.744Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tri Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0488",
		email: "tri.nguyen@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2025-05-10T10:40:54.240Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Lan Tran (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0489",
		email: "lan.tran@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2025-09-16T04:59:18.729Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Diep Vu (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0490",
		email: "diep.vu@team.ehub.com",
		lineManager: "Nhung Phan (EHUB - DS)",
		joinedAt: "2023-10-30T20:55:03.653Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Phuong Pham (EHUB - BE)",
		jobTitle: "Solution Architect Lead",
		employeeCode: "EHUB0492",
		email: "phuong.pham@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2026-05-03T17:28:12.420Z",
		role: "FUNCTION_LEAD",
	},
	{
		fullName: "Thao Le (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0494",
		email: "thao.le@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2025-02-08T12:52:23.968Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ha Tran (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0498",
		email: "ha.tran@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2026-01-12T14:39:41.385Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huy Nguyen (EHUB - MO)",
		jobTitle: "Mobile Engineer",
		employeeCode: "EHUB0495",
		email: "huy.nguyen@team.ehub.com",
		lineManager: "Hai Nguyen (EHUB - MO)",
		joinedAt: "2025-12-01T03:46:22.525Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hai Nguyen (EHUB - MO)",
		jobTitle: "Mobile Chapter Lead",
		employeeCode: "EHUB0496",
		email: "hai.nguyen@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2023-08-06T22:28:19.130Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Minh Ha (TMS - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0497",
		email: "minh.ha@team.ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2026-05-15T05:12:47.469Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Vu Tran (EHUB - BD)",
		jobTitle: "Business Development Manager",
		employeeCode: "EHUB0500",
		email: "vu.tran@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-04-06T18:49:53.453Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Van Dinh (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0499",
		email: "van.dinh@team.ehub.com",
		lineManager: "Sao Nguyen (EHUB - DS)",
		joinedAt: "2022-11-06T10:56:07.570Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thao Ho (EG - HR)",
		jobTitle: "Talent Acquisition Specialist",
		employeeCode: "EHUB0503",
		email: "thao.ho@team.ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2022-12-21T15:19:27.343Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhi Vo (ES - SP)",
		jobTitle: "Barista Staff",
		employeeCode: "EHUB0397",
		email: "nhi.vo@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2024-07-05T08:31:47.820Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thanh Do (EHUB - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0506",
		email: "thanh.do@team.ehub.com",
		lineManager: "Sao Nguyen (EHUB - DS)",
		joinedAt: "2024-01-20T15:25:53.041Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nga Nguyen (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0504",
		email: "nga.nguyen@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-12-03T07:31:16.192Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nam Phan (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0502",
		email: "nam.phan@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-11-09T22:31:46.199Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huy Le (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0505",
		email: "huy.le@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-12-23T13:51:16.861Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hoang Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0501",
		email: "hoang.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-05-23T06:58:50.256Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tuyen Tran (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0508",
		email: "tuyen.tran@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2023-02-12T06:33:09.711Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ngoc Dang (EHUB - BD)",
		jobTitle: "Business Development Executive",
		employeeCode: "EHUB0512",
		email: "ngoc.dang@ehub.com",
		lineManager: "Vu Tran (EHUB - BD)",
		joinedAt: "2023-01-29T16:35:38.612Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Vy Huynh (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0511",
		email: "vy.huynh@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2024-01-17T14:50:33.723Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hieu Nguyen (EHUB - PA)",
		jobTitle: "Product Lead",
		employeeCode: "EHUB0513",
		email: "hieu.nguyen@ehub.com",
		lineManager: "Dung Le (EHUB - PIDO)",
		joinedAt: "2025-04-21T15:17:41.130Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Amit Kothari (EHUB - CTO)",
		jobTitle: "Chief Technology Officer",
		employeeCode: "EHUB0002",
		email: "amit.kothari@team.ehub.com",
		lineManager: null, // CTO — top-level executive, no line manager
		joinedAt: "2024-09-26T19:17:43.730Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hoang Nguyen (TMS - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0517",
		email: "hoang.nguyenquoc@team.ehub.com",
		lineManager: "Sao Nguyen (EHUB - DS)",
		joinedAt: "2023-08-10T05:23:59.301Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tri Le (EHUB - PM)",
		jobTitle: "Project Manager",
		employeeCode: "EHUB0515",
		email: "tri.le@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-11-08T16:14:16.731Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Quy Do (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0518",
		email: "quy.do@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2022-12-12T08:14:02.254Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huy Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0516",
		email: "huy.nguyenphuoc@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-04-03T14:57:42.196Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Viet Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0519",
		email: "viet.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2023-12-04T18:14:25.193Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tra Pham (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0523",
		email: "tra.pham@ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-08-22T17:14:01.182Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Ngo (EG - FA)",
		jobTitle: "Finance & Account Admin",
		employeeCode: "EHUB0526",
		email: "dung.ngo@team.ehub.com",
		lineManager: "Phuong Huynh (EG - FA)",
		joinedAt: "2024-10-04T09:07:36.683Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hai Pham (EHUB - MO)",
		jobTitle: "Mobile Engineer",
		employeeCode: "EHUB0525",
		email: "hai.pham@team.ehub.com",
		lineManager: "Hai Nguyen (EHUB - MO)",
		joinedAt: "2025-05-01T09:14:38.563Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Chuong Mai (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0527",
		email: "chuong.mai@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-11-27T03:17:11.236Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ngan Nguyen (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0528",
		email: "ngan.nguyen@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2025-10-12T08:01:08.410Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Truc Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0531",
		email: "truc.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-03-21T04:10:29.910Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Linh Van (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0532",
		email: "linh.van@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2023-05-21T03:06:09.825Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Trung Bui (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0533",
		email: "trung.bui@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2025-12-25T17:15:56.466Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Trang Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0534",
		email: "trang.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-03-05T21:29:50.389Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Quoc Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0535",
		email: "quoc.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2023-01-22T03:25:19.768Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhan Dinh (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0536",
		email: "nhan.dinh@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-03-21T19:41:11.509Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dat Vo (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0537",
		email: "dat.vo@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-07-01T07:47:59.789Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Son Nguyen (TMS - BD)",
		jobTitle: "Business Development Executive",
		employeeCode: "EHUB0539",
		email: "son.nguyen@team.ehub.com",
		lineManager: "Loan Ngo (TMS - CS)",
		joinedAt: "2026-05-27T20:15:25.459Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hien Le (EHUB - AM)",
		jobTitle: "Account Executive",
		employeeCode: "EHUB0540",
		email: "hien.le@team.ehub.com",
		lineManager: "Tuyen Vo (EHUB - AM)",
		joinedAt: "2026-06-20T04:30:32.786Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhat Huynh (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0541",
		email: "nhat.huynh@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-06-18T15:35:21.871Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Phuong Huynh (EG - FA)",
		jobTitle: "Accounting Manager",
		employeeCode: "EHUB0543",
		email: "phuong.huynh@ehub.com",
		lineManager: "Ha Nguyen (EG - CFO)",
		joinedAt: "2025-02-14T02:48:27.068Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "My Tu (ES - SP)",
		jobTitle: "Space Operation Staff",
		employeeCode: "EHUB0546",
		email: "my.tu@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2023-02-09T16:43:20.770Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thi Ho (TMS - BD)",
		jobTitle: "Growth & Marketing Lead",
		employeeCode: "EHUB0544",
		email: "thi.ho@sotrams.ecaps",
		lineManager: "Yung Nguyen (EHUB - CMO)",
		joinedAt: "2026-04-16T09:08:41.379Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Hoang Nguyen (EHUB - BE)",
		jobTitle: "Backend Engineer",
		employeeCode: "EHUB0547",
		email: "quochoang.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-02-06T21:35:28.255Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Van Tran (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0548",
		email: "van.tran@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-11-11T14:36:06.357Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nhi Pham (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0549",
		email: "nhi.pham@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2023-10-03T11:40:35.195Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Kim Thi (TMS - BE)",
		jobTitle: "Technical Lead",
		employeeCode: "EHUB0550",
		email: "kim.thi@sotrams.ecaps",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-10-16T02:35:54.173Z",
		role: "FUNCTION_LEAD",
	},
	{
		fullName: "Quynh Vo (TMS - CEO)",
		jobTitle: "Chief Executive Officer",
		employeeCode: "EHUB0545",
		email: "quynh.vo@ehub.com",
		lineManager: null, // CEO — top-level executive, no line manager
		joinedAt: "2024-02-27T18:17:52.523Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Oanh Do (TMS - DS)",
		jobTitle: "Product Designer",
		employeeCode: "EHUB0551",
		email: "oanh.do@team.ehub.com",
		lineManager: "Sao Nguyen (EHUB - DS)",
		joinedAt: "2023-10-09T04:31:51.654Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Lam Le (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "EHUB0553",
		email: "lam.le@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2023-02-23T07:07:33.652Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thy Nguyen (EG - HR)",
		jobTitle: "Human Resources Specialist",
		employeeCode: "EHUB0554",
		email: "thy.nguyen@team.ehub.com",
		lineManager: "Anh Nguyen (EG - HR)",
		joinedAt: "2023-09-08T06:15:04.547Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Sang Vuong (EHUB - PA)",
		jobTitle: "Business Analyst",
		employeeCode: "EHUB0555",
		email: "sang.vuong@team.ehub.com",
		lineManager: "Hieu Nguyen (EHUB - PA)",
		joinedAt: "2023-12-01T23:27:26.952Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Truc Le (EHUB - PM)",
		jobTitle: "Project Manager",
		employeeCode: "EHUB0552",
		email: "truc.le@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2025-01-19T05:43:04.261Z",
		role: RoleType.PROJECT_MANAGER,
	},
	{
		fullName: "Linh Nguyen (EHUB - QA)",
		jobTitle: "Quality Assurance Engineer",
		employeeCode: "EHUB0557",
		email: "trieulinh.nguyen@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2023-02-13T01:56:22.478Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Huong Nguyen (EG - CA)",
		jobTitle: "CEO Assistant - Finance Coordinator",
		employeeCode: "EHUB0558",
		email: "huong.nguyen@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2023-08-28T19:27:11.855Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thuan Nguyen (EHUB - MO)",
		jobTitle: "Mobile Engineer",
		employeeCode: "EHUB0559",
		email: "thuan.nguyen@team.ehub.com",
		lineManager: "Hai Nguyen (EHUB - MO)",
		joinedAt: "2025-10-10T17:47:12.585Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ty Nguyen (EHUB - BE)",
		jobTitle: "DevOps Engineer",
		employeeCode: "EHUB0560",
		email: "ty.nguyen@team.ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2024-01-31T15:48:43.833Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Linh Nguyen (EHUB - FE)",
		jobTitle: "Frontend Engineer",
		employeeCode: "EHUB0561",
		email: "vungoclinh.nguyen@team.ehub.com",
		lineManager: "Phat Nguyen (EHUB - FE)",
		joinedAt: "2024-04-24T19:18:48.648Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tram Le (TMS - BD)",
		jobTitle: "Marketing Executive",
		employeeCode: "EHUB0563",
		email: "tram.le@team.ehub.com",
		lineManager: "Thi Ho (TMS - BD)",
		joinedAt: "2025-04-16T16:33:40.738Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Phuc Pham (EG - CA)",
		jobTitle: "CEO Assistant - Business Development Coordinator",
		employeeCode: "EHUB0564",
		email: "phuc.pham@ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2024-06-24T16:31:59.076Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Tai Vo (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0566",
		email: "tai.vo@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-01-11T17:20:30.135Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nguyen Tran (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0565",
		email: "nguyen.tran@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-01-16T21:03:45.780Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Ba Le (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0567",
		email: "ba.le@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-09-08T05:43:16.824Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Kien Nguyen (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0576",
		email: "kien.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2025-05-08T10:31:41.400Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Linh Do (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0574",
		email: "linh.do@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2024-04-03T02:02:03.059Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hieu Nguyen (EHUB - PDO Intern)",
		jobTitle: "Software Engineer Intern",
		employeeCode: "EHUB0575",
		email: "thanhhieu.nguyen@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2026-04-22T04:29:00.278Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Linh Ha (TMS - BD)",
		jobTitle: "Business Development Intern",
		employeeCode: "EHUB0568",
		email: "linh.ha@team.ehub.com",
		lineManager: "Loan Ngo (TMS - CS)",
		joinedAt: "2024-02-20T07:15:56.754Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Thao Mac (ES - SP)",
		jobTitle: "Space Community Intern",
		employeeCode: "EHUB0569",
		email: "thao.mac@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2023-05-09T08:28:56.912Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Han Tran (EHUB - MKT)",
		jobTitle: "Marketing Executive",
		employeeCode: "EHUB0571",
		email: "han.tran@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2022-10-03T01:30:35.740Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Long Le (TMS - BD)",
		jobTitle: "Business Development Executive",
		employeeCode: "EHUB0573",
		email: "long.le@sotrams.ecaps",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2023-06-17T16:46:38.241Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Dung Thai (EG - FA)",
		jobTitle: "Finance & Accounting",
		employeeCode: "EHUB0577",
		email: "dung.thai@team.ehub.com",
		lineManager: "Phuong Huynh (EG - FA)",
		joinedAt: "2024-05-16T00:30:36.463Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hoang Nguyen (EHUB - WD)",
		jobTitle: "Web Developer",
		employeeCode: "EHUB0578",
		email: "haihoang.nguyen@team.ehub.com",
		lineManager: "Nam Nguyen (EHUB - WD)",
		joinedAt: "2023-10-13T07:22:09.527Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Sinh Nguyen (EHUB - BD)",
		jobTitle: "Business Development Executive",
		employeeCode: "",
		email: "sinh.nguyen@ehub.com",
		lineManager: "Vu Tran (EHUB - BD)",
		joinedAt: "2024-12-24T06:12:14.901Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Loc Nguyen (TMS - BD)",
		jobTitle: "Solution Consultant",
		employeeCode: "EHUB0581",
		email: "loc.nguyen@team.ehub.com",
		lineManager: "Trang Tran (EG - CEO)",
		joinedAt: "2026-04-16T16:52:23.848Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Trinh Le (TMS - BD)",
		jobTitle: "Business Development Lead",
		employeeCode: "EHUB0582",
		email: "camtrinh.le@team.ehub.com",
		lineManager: "MinhMai Phan (TMS - CPO)",
		joinedAt: "2024-03-19T05:46:28.286Z",
		role: "FUNCTION_LEAD",
	},
	{
		fullName: "Yung Nguyen (EHUB - CMO)",
		jobTitle: "Chief Marketing Officer",
		employeeCode: "EHUB0048",
		email: "yung.nguyen@ehub.com",
		lineManager: null, // CMO — top-level executive, no line manager
		joinedAt: "2023-11-29T10:32:55.333Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Diem Do (EHUB - MKT)",
		jobTitle: "Digital Marketing Executive",
		employeeCode: "EHUB0078",
		email: "diem.do@team.ehub.com",
		lineManager: "Trang Tran (EHUB - MKT)",
		joinedAt: "2025-01-19T18:19:39.781Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Nam Nguyen (EHUB - WD)",
		jobTitle: "Web Development Lead",
		employeeCode: "EHUB0014",
		email: "nam.nguyen@ehub.com",
		lineManager: DemoConfig.PROJECT_MANAGER.FULLNAME,
		joinedAt: "2024-11-20T15:34:18.551Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Trang Tran (EHUB - MKT)",
		jobTitle: "Digital Marketing Lead",
		employeeCode: "EHUB0055",
		email: "thitrang.tran@ehub.com",
		lineManager: "Yung Nguyen (EHUB - CMO)",
		joinedAt: "2023-12-24T01:04:53.815Z",
		role: RoleType.LINE_MANAGER,
	},
	{
		fullName: "Phuong Nguyen (EHUB - ML/AI)",
		jobTitle: "AI Engineer",
		employeeCode: "",
		email: "phuong.nguyenduy@team.ehub.com",
		lineManager: DemoConfig.LINE_MANAGER.FULLNAME,
		joinedAt: "2023-01-09T03:32:12.437Z",
		role: RoleType.EMPLOYEE,
	},
	{
		fullName: "Hanh Nguyen (ES - SP)",
		jobTitle: "Barista Staff",
		employeeCode: "EHUB0570",
		email: "cafe@team.ehub.com",
		lineManager: "Thanh Le (ES - SP)",
		joinedAt: "2025-09-16T10:01:59.028Z",
		role: RoleType.EMPLOYEE,
	},
];
